// <auto-generated />
namespace VKR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_200418 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_200418));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201854543_DB_200418"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
