// <auto-generated />
namespace VKR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_0305183 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_0305183));
        
        string IMigrationMetadata.Id
        {
            get { return "201805031843512_DB_0305183"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
